<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Platform</name>
   <tag></tag>
   <elementGuidId>a4d43dd2-0c73-4ddc-8121-324dcaf4b765</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='katalon_header']/section[2]/div/div/div/div[2]/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>cd2ea53a-bcd5-483d-9f7b-f764b8a178dc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>top_nav_title</value>
      <webElementGuid>7fe543f5-d10a-4718-aca6-095c921cd0f1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-traffic-agent-last-action-id</name>
      <type>Main</type>
      <value>ee4cba09-4129-47a4-bb43-13c876abca83</value>
      <webElementGuid>e4ebacb6-5e7a-47a8-a29f-dcddc46dcd32</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-hoverable</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>9be4148b-1039-4533-9be8-7db5739833c5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-rnd-last-action-id</name>
      <type>Main</type>
      <value>17c32623-7af8-41f2-9dcf-b82892394a83</value>
      <webElementGuid>f73ec678-2443-4461-803f-4296bcfc0276</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Platform</value>
      <webElementGuid>8721baee-1ded-436f-9702-867c30d413f9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;katalon_header&quot;)/section[@class=&quot;rebrand_header&quot;]/div[@class=&quot;wrap_container&quot;]/div[@class=&quot;left_logo_and_topnav&quot;]/div[@class=&quot;katalon_topnav&quot;]/div[@class=&quot;top_nav_item have_child_menu&quot;]/div[@class=&quot;top_nav_title&quot;]</value>
      <webElementGuid>f9afd0f0-4331-44ac-b265-04fe767f0fdc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='katalon_header']/section[2]/div/div/div/div[2]/div</value>
      <webElementGuid>70b67088-f5ab-49ac-ba5a-1a54b68bccd2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Low cost, high ROI'])[1]/following::div[3]</value>
      <webElementGuid>0f6e3895-9167-427c-b336-4521c38b3008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Innovation &amp; AI'])[1]/following::div[5]</value>
      <webElementGuid>5790856e-4048-4347-9da9-a19d1df37ddb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform'])[2]/preceding::div[1]</value>
      <webElementGuid>58a0a280-8153-4169-ba5e-20adf6658044</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Platform Overview'])[1]/preceding::div[4]</value>
      <webElementGuid>c426f6d3-dc83-44ef-8b3f-46640dad8e1e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Platform']/parent::*</value>
      <webElementGuid>ee86e6b3-8aae-4363-be9b-786f7b519289</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div</value>
      <webElementGuid>b3e05de4-f7e0-4dbf-9f43-101078d91166</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'Platform' or . = 'Platform')]</value>
      <webElementGuid>0f7b6d74-1d5a-460f-8352-e8b0e55a2a9a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
